{
 "title": "Kuzzle",
 "description": "Kuzzle monitoring example dashboard using the Prometheus plugin v4",
 "tags": [
  "kuzzle",
  "nodejs"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "nodeId", "label": "nodeId", "query": { "query": "label_values(nodeId)" } }
  ]
 },
 "panels": [
  {
   "title": "Status code 500 per Node",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(nodeId) (rate(kuzzle_api_request_duration_ms_count{status=~\"5.+\",nodeId=~\"$nodeId\"}[$__rate_interval]) * 50)",
     "legendFormat": "{{nodeId}}"
    }
   ]
  },
  {
   "title": "Status code 500 per API action",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(action, controller) (rate(kuzzle_api_request_duration_ms_count{status=~\"5.+\",nodeId=~\"$nodeId\"}[$__rate_interval]) * 50)",
     "legendFormat": "{{controller}} - {{action}}"
    }
   ]
  },
  {
   "title": "Active connections per Node",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by(nodeId) (kuzzle_network_connections{nodeId=~\"$nodeId\"})",
     "legendFormat": "{{nodeId}}"
    }
   ]
  },
  {
   "title": "Active connections per protocol",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": " group by(protocol) (kuzzle_network_connections{nodeId=~\"$nodeId\"})",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Concurrent request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "kuzzle_api_concurrent_requests{nodeId=~\"$nodeId\"}",
     "legendFormat": "{{nodeId}}"
    }
   ]
  },
  {
   "title": "Pending requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
   "targets": [
    {
     "expr": "kuzzle_api_pending_requests{nodeId=~\"$nodeId\"}",
     "legendFormat": "{{nodeId}}"
    }
   ]
  },
  {
   "title": "Active Realtime Subscriptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
   "targets": [
    {
     "expr": "sum by(nodeId) (kuzzle_realtime_subscriptions{nodeId=~\"$nodeId\"})",
     "legendFormat": "{{nodeId}}"
    }
   ]
  },
  {
   "title": "Requests per Kuzzle node",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (nodeId) (rate(kuzzle_api_request_duration_ms_count{nodeId=~\"$nodeId\"}[$__rate_interval]))",
     "legendFormat": "{{ nodeId }} "
    }
   ]
  },
  {
   "title": "Requests per API route",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (controller, action)(rate(kuzzle_api_request_duration_ms_count{nodeId=~\"$nodeId\"}[$__rate_interval]))",
     "legendFormat": "{{controller}} - {{action}}"
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Response latency per Node",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max by (nodeId) (histogram_quantile(0.95, rate(kuzzle_api_request_duration_ms_bucket{nodeId=~\"$nodeId\"}[$__rate_interval])))",
     "legendFormat": "{{nodeId}}"
    }
   ]
  },
  {
   "title": "Reponse latency per API route",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max by (controller, action) (histogram_quantile(0.95, rate(kuzzle_api_request_duration_ms_bucket{nodeId=~\"$nodeId\"}[$__rate_interval])))",
     "legendFormat": "{{controller}} - {{action}}"
    }
   ]
  }
 ]
}