{
 "title": "NodeJS process",
 "description": "node.js prometheus client basic metrics",
 "tags": [ "nodejs" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "nodeId",
    "label": "nodeId",
    "query": {
     "query": "label_values(nodejs_version_info, nodeId)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Process CPU Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_user_seconds_total{nodeId=~\"$nodeId\"}[2m]) * 100",
     "legendFormat": "User CPU"
    },
    {
     "expr": "irate(process_cpu_system_seconds_total{nodeId=~\"$nodeId\"}[2m]) * 100",
     "legendFormat": "Sys CPU"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{nodeId=~\"$nodeId\"}",
     "legendFormat": "Node.js Event Loop Lag"
    }
   ]
  },
  {
   "title": "Node.js Version",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(nodejs_version_info{nodeId=~\"$nodeId\"}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Process Restart Times",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(process_start_time_seconds{nodeId=~\"$nodeId\"}[$__rate_interval]))",
     "legendFormat": "{{nodeId}}"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{nodeId=~\"$nodeId\"}",
     "legendFormat": "Process Memory"
    },
    {
     "expr": "nodejs_heap_size_total_bytes{nodeId=~\"$nodeId\"}",
     "legendFormat": "Heap Total"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{nodeId=~\"$nodeId\"}",
     "legendFormat": "Heap Used"
    },
    {
     "expr": "nodejs_external_memory_bytes{nodeId=~\"$nodeId\"}",
     "legendFormat": "External Memory"
    }
   ]
  },
  {
   "title": "Active Handlers/Requests Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nodejs_active_handles_total{nodeId=~\"$nodeId\"}",
     "legendFormat": "Active Handler"
    },
    {
     "expr": "nodejs_active_requests_total{nodeId=~\"$nodeId\"}",
     "legendFormat": "Active Request"
    }
   ]
  },
  {
   "title": "Heap Total Detail",
   "type": "graph",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_total_bytes{nodeId=~\"$nodeId\"}",
     "legendFormat": "Heap Total - {{space}}"
    }
   ]
  },
  {
   "title": "Heap Used Detail",
   "type": "graph",
   "gridPos": { "h": 15, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_used_bytes{nodeId=~\"$nodeId\"}",
     "legendFormat": "Heap Used - {{space}}"
    }
   ]
  },
  {
   "title": "Heap Available Detail",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_available_bytes{nodeId=~\"$nodeId\"}",
     "legendFormat": "Heap Used - {{space}}"
    }
   ]
  }
 ]
}