{
 "title": "Kuzzle",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Active Rooms",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(kuzzle_active_rooms{job=\"kuzzle\"})",
     "legendFormat": "{{ nodeHost }}"
    }
   ]
  },
  {
   "title": "Requests per Kuzzle node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (nodeHost, nodeMAC, nodeIP) (rate(kuzzle_requests_count{job=\"kuzzle\"}[30s]))",
     "legendFormat": "IP: {{ nodeIP }} - host: {{ nodeHost }} "
    }
   ]
  },
  {
   "title": "Requests per API route",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (controller, action)(irate(kuzzle_requests_count{job=\"kuzzle\", event=\"request:onSuccess\"}[30s]))",
     "legendFormat": "{{controller}} - {{action}}"
    }
   ]
  },
  {
   "title": "Reponse latency per API route",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by (controller, action) (histogram_quantile(0.95, irate(kuzzle_requests_bucket{job=\"kuzzle\", event=\"request:onSuccess\"}[30s])))",
     "legendFormat": "{{controller}} - {{action}}"
    }
   ]
  }
 ]
}