version: '3'

services:
  kuzzle:
    image: kuzzleio/plugin-dev:${KUZZLE_DOCKER_TAG:-latest}
    command: /run.sh
    volumes:
      - "./run.sh:/run.sh"
      - "../:/var/app/plugins/enabled/kuzzle-plugin-prometheus"
      - "../config/kuzzlerc:/etc/kuzzlerc"
      - "../config/pm2.json:/config/pm2.json"
    cap_add:
      - SYS_PTRACE
    ulimits:
      nofile: 65536
    sysctls:
      - net.core.somaxconn=8192
    depends_on:
      - redis
      - elasticsearch
    ports:
      - "7512:7512"
    environment:
      - kuzzle_services__db__client__host=http://elasticsearch:9200
      - kuzzle_services__internalCache__node__host=redis
      - kuzzle_services__memoryStorage__node__host=redis
      - NODE_ENV=development
      - NODE_LTS=8
      - DEBUG=kuzzle:plugins

  redis:
    image: redis:5

  elasticsearch:
    image: kuzzleio/elasticsearch:5.6.10
    ulimits:
      nofile: 65536
    environment:
      - cluster.name=kuzzle
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    depends_on:
      - kuzzle
    volumes:
      - "../config/prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    links:
      - kuzzle

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - "../config/grafana.yml:/etc/grafana/provisioning/datasources/datasource.yaml"
    links:
      - prometheus
