name: Lint
description: Run ESLint and the TypeScript check
runs:
  using: "composite"
  steps:
    - name: Run linter
      shell: bash
      run: |
           npm ci
           npm run test:lint
           npm run test:types
